# Generated by Django 5.2.1 on 2025-05-15 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_track_artists_alter_track_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='is_Prenium',
            new_name='is_Premium',
        ),
    ]
