# Generated by Django 5.2.1 on 2025-05-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_remove_track_artists_track_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='artist',
            new_name='artists',
        ),
    ]
